version: '3'
services:
  app:
    tty: true
    container_name: 'sinatra-app'
    build: .
    command: bundle exec unicorn -c unicorn.conf
    volumes:
      - ./app:/app
    ports:
      - "5000:5000"
