version: '3'
services:
  app:
    tty: true
    container_name: 'sinatra-app'
    build: .
    command: bundle exec unicorn -c unicorn.conf
    volumes:
      - ./app:/app
    ports:
      - "15000:5000"
    depends_on:
      - mysql
      - cache
      - redis-01
      - fluentd

  mysql:
    image: mysql:5.7
    ports:
      - "13306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_ALLOW_EMPTY_PASSWORD=no
      - MYSQL_USER=sinatra
      - MYSQL_PASSWORD=sinatra_password=JST
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - mysql:/var/lib/mysql

  cache:
    image: memcached:1.5.20

  redis-01:
    image: redis:5.0.6
    ports:
      - "16379:6379"

  fluentd:
    build: ./fluentd
    volumes:
      - ./fluentd/config:/fluentd/etc
    links:
      - elasticsearch
    ports:
      - "24224:24224"
    depends_on:
      - elasticsearch

  elasticsearch:
    image: elasticsearch:7.4.2
    environment:
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 19200:9200
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data

  kibana:
    image: kibana:7.4.2
    ports:
      - 15601:5601
    links:
      - elasticsearch:elasticsearch

volumes:
  mysql:
    driver: local
  elasticsearch:
    driver: local
